# Generated by Django 3.2.6 on 2021-08-10 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogmeta_navlinks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmeta',
            old_name='name',
            new_name='meta',
        ),
    ]
