# Generated by Django 3.2.6 on 2021-08-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_name_blogmeta_meta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NavLinks',
            new_name='NavLink',
        ),
    ]
