# Generated by Django 3.2.6 on 2021-08-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
